name: Tests
on: [push, pull_request]
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
      - name: Install fuse
        run: sudo apt-get install -qq fuse
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./...
  test-osx:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
      - name: Install fuse
        run: brew update && brew cask install osxfuse
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./...
