name: Tests
on: [push, pull_request]
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
      - name: Install fuse
        run: sudo apt-get install -qq fuse
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./...
  test-osx:
    runs-on: macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
      - name: Install fuse
        run: brew update && brew install --cask osxfuse
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./...
